services:
  mysql:
    image: mysql:8.2.0
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${GRIM_MYSQL_DATABASE}
      MYSQL_USER: ${GRIM_MYSQL_USER}
      MYSQL_PASSWORD: ${GRIM_MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      DEFAULT_AUTHENTICATION_PLUGIN: caching_sha2_password
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6380:6379
    volumes:
      - ./redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
volumes:
  mysql-data:
  redis-data: