services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      # Database
      DB_HOST: mysql
      DB_PORT: 3306
      GRIM_MYSQL_USER: ${GRIM_MYSQL_USER}
      GRIM_MYSQL_PASSWORD: ${GRIM_MYSQL_PASSWORD}
      GRIM_MYSQL_DATABASE: ${GRIM_MYSQL_DATABASE}

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}

      # AWS S3
      GRIM_AWS_ACCESS_KEY: ${GRIM_AWS_ACCESS_KEY}
      GRIM_AWS_SECRET_KEY: ${GRIM_AWS_SECRET_KEY}
      GRIM_AWS_REGION: ${GRIM_AWS_REGION}
      GRIM_AWS_BUCKET: ${GRIM_AWS_BUCKET}

      # JWT
      GRIM_JWT_SECRET: ${GRIM_JWT_SECRET}
      GRIM_JWT_EXPIRATION_MS: ${GRIM_JWT_EXPIRATION_MS}
      GRIM_JWT_REFRESH_EXPIRATION_MS: ${GRIM_JWT_REFRESH_EXPIRATION_MS}
      GRIM_CRYPTO_AES_SECRET: ${GRIM_CRYPTO_AES_SECRET}

      # OAuth - KAKAO
      GRIM_KAKAO_REST_API_KEY: ${GRIM_KAKAO_REST_API_KEY}
      GRIM_KAKAO_CLIENT_SECRET_KEY: ${GRIM_KAKAO_CLIENT_SECRET_KEY}
      GRIM_KAKAO_CALLBACK_URI_LOCAL: ${GRIM_KAKAO_CALLBACK_URI_LOCAL}
      GRIM_KAKAO_CALLBACK_URI_PROD: ${GRIM_KAKAO_CALLBACK_URI_PROD}

      # OAuth - GOOGLE
      GRIM_GOOGLE_CLIENT_KEY: ${GRIM_GOOGLE_CLIENT_KEY}
      GRIM_GOOGLE_CLIENT_SECRET_KEY: ${GRIM_GOOGLE_CLIENT_SECRET_KEY}
      GRIM_GOOGLE_CALLBACK_URI_LOCAL: ${GRIM_GOOGLE_CALLBACK_URI_LOCAL}
      GRIM_GOOGLE_CALLBACK_URI_PROD: ${GRIM_GOOGLE_CALLBACK_URI_PROD}

      # OAuth - NAVER
      GRIM_NAVER_CLIENT_KEY: ${GRIM_NAVER_CLIENT_KEY}
      GRIM_NAVER_CLIENT_SECRET_KEY: ${GRIM_NAVER_CLIENT_SECRET_KEY}
      GRIM_NAVER_CALLBACK_URI_LOCAL: ${GRIM_NAVER_CALLBACK_URI_LOCAL}
      GRIM_NAVER_CALLBACK_URI_PROD: ${GRIM_NAVER_CALLBACK_URI_PROD}

      # Email
      GRIM_TEST_EMAIL_USER: ${GRIM_TEST_EMAIL_USER}
      GRIM_TEST_EMAIL_PASSWORD: ${GRIM_TEST_EMAIL_PASSWORD}

    depends_on:
      - mysql
      - redis
    networks:
      - app-network

networks:
  app-network:
    external: true
