services:
  mysql:
    image: mysql:8.2.0
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${GRIM_MYSQL_DATABASE}
      MYSQL_USER: ${GRIM_MYSQL_USER}
      MYSQL_PASSWORD: ${GRIM_MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      DEFAULT_AUTHENTICATION_PLUGIN: caching_sha2_password
    networks:
      - app-network
  mongodb:
    image: mongo:6.0
    restart: always
    container_name: grimeet
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    external: true