services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      DB_HOST: mysql
      DB_PORT: 3307
      DB_USER: ${GRIM_MYSQL_USER}
      DB_PASSWORD: ${GRIM_MYSQL_PASSWORD}
      DB_NAME: ${GRIM_MYSQL_DATABASE}
      REDIS_HOST: redis
      REDIS_PORT: 6380
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

networks:
  app-network:
    external: true