spring:
  application:
    name: grimeet
  profiles:
    active: oauth, mail, swagger, s3
  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: jdbc:${GRIM_DB_HOST}://${GRIM_DB_HOST}:${GRIM_DB_PORT}/grim
    username: ${GRIM_MYSQL_USER}
    password: ${GRIM_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  hibernate:
    ddl-auto: update

  sql:
    init:
      mode: always

  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 0

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${GRIM_JWT_SECRET}
  expirationMs: ${GRIM_JWT_EXPIRATION_MS}
  refreshExpirationMs: ${GRIM_JWT_REFRESH_EXPIRATION_MS}
  token-prefix: Bearer
  header: Authorization

crypto:
  aes:
    secret: ${GRIM_CRYPTO_AES_SECRET}

cookie:
  maxAge:
    access: ${GRIM_JWT_EXPIRATION_MS}