spring:
  application:
    name: grimeet
  profiles:
    include: oauth
  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: jdbc:mysql://mysql:3306/grim?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${GRIM_MYSQL_USER}
    password: ${GRIM_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  hibernate:
    ddl-auto: update

  sql:
    init:
      mode: always

  data:
    redis:
      host: redis
      port: 6379

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GRIM_TEST_EMAIL_USER}
    password: ${GRIM_TEST_EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    verification:
      auth-code-ttl: 900

cloud:
  aws:
    credentials:
      accessKey: ${GRIM_AWS_ACCESS_KEY}
      secretKey: ${GRIM_AWS_SECRET_KEY}
    region:
      static: ${GRIM_AWS_REGION}
    s3:
      bucketName: ${GRIM_AWS_BUCKET}
    stack:
      auto: false

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${GRIM_JWT_SECRET}
  expirationMs: ${GRIM_JWT_EXPIRATION_MS}
  refreshExpirationMs: ${GRIM_JWT_REFRESH_EXPIRATION_MS}
  token-prefix: Bearer
  header: Authorization

springdoc:
  packages-to-scan: com.grimeet.grimeet
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    doc-expansion: list
    filter: true
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method
    deep-linking: true
    syntax-highlight:
      activated: true

cookie:
  maxAge:
    access: ${GRIM_JWT_EXPIRATION_MS}
